import { useState, useEffect, useRef } from 'react';
import { api } from '@/lib/api';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Bot, User, Send, MessageSquare, X } from 'lucide-react';

interface Message {
  id: string;
  content: string;
  sender: 'user' | 'bot';
  timestamp: Date;
}

const ChatBot = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState<Message[]>([
    {
      id: '1',
      content: "Hello! I'm Frank's AI assistant. I can help you learn more about his skills, experience, or projects. What would you like to know?",
      sender: 'bot',
      timestamp: new Date()
    }
  ]);
  const [inputValue, setInputValue] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [analysis, setAnalysis] = useState<null | {
    strengths?: string[];
    weaknesses?: string[];
    improvements?: string[];
    applications?: string[];
    supportingEvidence?: Record<string, string>;
    error?: string;
    raw?: string;
  }>(null);

  // Responses are now generated by the backend via /api/chat

  const endOfMessagesRef = useRef<HTMLDivElement | null>(null);
  const scrollToBottom = () => {
    endOfMessagesRef.current?.scrollIntoView({ behavior: 'smooth' });
  };
  useEffect(() => {
    if (isOpen) scrollToBottom();
  }, [messages, isOpen]);

  const handleSendMessage = async () => {
    if (!inputValue.trim()) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      content: inputValue,
      sender: 'user',
      timestamp: new Date()
    };

    setMessages(prev => [...prev, userMessage]);

    setInputValue('');
    setIsLoading(true);
    try {
      const data = await api<{ reply: string }>("/api/chat", {
        method: 'POST',
        body: JSON.stringify({ message: userMessage.content })
      });
      const botMessage: Message = {
        id: (Date.now() + 1).toString(),
        content: data.reply,
        sender: 'bot',
        timestamp: new Date()
      };
      setMessages(prev => [...prev, botMessage]);
    } catch (e) {
      const botMessage: Message = {
        id: (Date.now() + 1).toString(),
        content: 'Sorry, I had trouble reaching the assistant service.',
        sender: 'bot',
        timestamp: new Date()
      };
      setMessages(prev => [...prev, botMessage]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      handleSendMessage();
    }
  };

  return (
    <>
      {/* Chat Toggle Button */}
      <Button
        onClick={() => setIsOpen(!isOpen)}
        className="fixed bottom-6 right-6 z-50 w-14 h-14 rounded-full bg-hero-gradient hover:opacity-90 transition-smooth shadow-glow-primary"
        size="icon"
      >
        {isOpen ? <X className="h-6 w-6" /> : <MessageSquare className="h-6 w-6" />}
      </Button>

      {/* Chat Window */}
      {isOpen && (
        <Card className="fixed bottom-24 right-6 z-40 w-96 h-[500px] bg-card-gradient border-border/50 shadow-glow-primary/20 flex flex-col">
          {/* Header */}
          <div className="p-4 border-b border-border/50 bg-hero-gradient rounded-t-lg">
            <div className="flex items-center space-x-3">
              <div className="w-10 h-10 bg-white/20 rounded-full flex items-center justify-center">
                <Bot className="h-6 w-6 text-white" />
              </div>
              <div>
                <h3 className="font-semibold text-white">AI Assistant</h3>
              </div>
            </div>
          </div>

          {/* Messages */}
          <ScrollArea className="flex-1 p-4">
            <div className="space-y-4">
              {messages.map((message) => (
                <div
                  key={message.id}
                  className={`flex ${message.sender === 'user' ? 'justify-end' : 'justify-start'}`}
                >
                  <div
                    className={`max-w-[80%] p-3 rounded-lg ${
                      message.sender === 'user'
                        ? 'bg-primary text-primary-foreground'
                        : 'bg-secondary/50 text-foreground'
                    }`}
                  >
                    <div className="flex items-start space-x-2">
                      {message.sender === 'bot' && (
                        <Bot className="h-4 w-4 mt-0.5 text-primary flex-shrink-0" />
                      )}
                      {message.sender === 'user' && (
                        <User className="h-4 w-4 mt-0.5 text-primary-foreground flex-shrink-0" />
                      )}
                      <p className="text-sm leading-relaxed">{message.content}</p>
                    </div>
                  </div>
                </div>
              ))}
              <div ref={endOfMessagesRef} />
            </div>
          </ScrollArea>

          {/* Analysis render */}
          {analysis && (
            <div className="px-4 pt-2 space-y-4">
              {analysis.error && (
                <p className="text-sm text-red-500">{analysis.error}</p>
              )}
              {analysis.strengths && analysis.strengths.length > 0 && (
                <div>
                  <h4 className="text-sm font-semibold mb-1">Strengths</h4>
                  <ul className="list-disc pl-5 space-y-1 text-sm">
                    {analysis.strengths.map((s, i) => (
                      <li key={i}>{s}</li>
                    ))}
                  </ul>
                </div>
              )}
              {analysis.weaknesses && analysis.weaknesses.length > 0 && (
                <div>
                  <h4 className="text-sm font-semibold mb-1">Weaknesses</h4>
                  <ul className="list-disc pl-5 space-y-1 text-sm">
                    {analysis.weaknesses.map((s, i) => (
                      <li key={i}>{s}</li>
                    ))}
                  </ul>
                </div>
              )}
              {analysis.improvements && analysis.improvements.length > 0 && (
                <div>
                  <h4 className="text-sm font-semibold mb-1">Improvements</h4>
                  <ul className="list-disc pl-5 space-y-1 text-sm">
                    {analysis.improvements.map((s, i) => (
                      <li key={i}>{s}</li>
                    ))}
                  </ul>
                </div>
              )}
              {analysis.applications && analysis.applications.length > 0 && (
                <div>
                  <h4 className="text-sm font-semibold mb-1">Applications</h4>
                  <ul className="list-disc pl-5 space-y-1 text-sm">
                    {analysis.applications.map((s, i) => (
                      <li key={i}>{s}</li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          )}

          {/* Input */}
          <div className="p-4 border-t border-border/50">
            <div className="flex space-x-2">
              <Input
                value={inputValue}
                onChange={(e) => setInputValue(e.target.value)}
                onKeyPress={handleKeyPress}
                placeholder={isLoading ? 'Analyzing...' : 'Ask a question...'}
                className="flex-1 bg-secondary/20 border-border/50 focus:border-primary"
              />
              <Button
                onClick={handleSendMessage}
                size="icon"
                className="bg-primary hover:bg-primary/90"
                disabled={isLoading}
              >
                <Send className="h-4 w-4" />
              </Button>
            </div>
          </div>
        </Card>
      )}
    </>
  );
};

export default ChatBot;